server:
  port: 9001

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          lower-case-service-id: true
          enabled: true
      routes:
      - id: admin_consumer_route
        uri: lb://admin-consumer
        predicates:
          - Path=/api/admin/**
      #
      - id: before_baidu_route
        uri: http://www.baidu.com
        predicates:
          - Before=2021-12-25T23:59:59.789+08:00

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
