server:
  port: 8101

spring:
  application:
    name: admin-consumer

feign:
  hystrix:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,hystrix.stream

eureka:
  client:
    serviceUrl:
      defaultZone: http://ds.com:8761/eureka/
