base:
  mysql: rm-2vc324bw1c916bvdfeo.mysql.cn-chengdu.rds.aliyuncs.com

server:
  port: 8201

spring:
  application:
    name: user-service
  #MySql 配置
  datasource:
    url: jdbc:mysql://${base.mysql}/example?serverTimezone=Hongkong&useUnicode=true&useSSL=false&characterEncoding=utf8
    username: ds
    password: test@123
    driver-class-name: com.mysql.cj.jdbc.Driver
  #Redis 配置
  redis:
    # Redis服务器地址
    host: dus.com
    # Redis数据库索引（默认为0）
    database: 0
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password: test@123
    # 链接超时时间 单位 ms（毫秒）
    timeout: 3000
    # Redis 线程池设置
    lettuce:
      pool:
        # 连接池最大连接数（使用负值表示没有限制） 默认 8
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        max-wait: -1
        # 连接池中的最大空闲连接 默认 8
        max-idle: 8
        # 连接池中的最小空闲连接 默认 0
        min-idle: 0
  # json 时间格式化
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka.ds.com:8761/eureka/
